language: php
php:
    - 7.2
services:
    - docker
install:
    - composer install
    - docker build -t rss-server .
    - docker run -d -p 127.0.0.1:80:80 --name rss-server rss-server
script:
  - phpunit
after_failure:
  - docker logs -f rss-server