language: php
php:
    - 7.2
services:
    - docker
before_install:
    - phpenv config-add apcu.ini
install:
    - docker build -t rss-server .
    - docker run -d -p 127.0.0.1:80:80 --name rss-server rss-server
before_script:
  - phpenv config-rm xdebug.ini
script:
  - composer install
  - phpunit
after_failure:
  - docker logs rss-server